### PR TITLE
Update Challenge.service.ts

### PR DESCRIPTION
**Pull request by vitaly-t**
better querying ;)

### CODE REVIEW

**Comment by woolfi182** [comment]
Hello, Vitaly. I see your changes and I found my fault (I had copied the body of a function from another function which I removed before a commit). Thank's for that.
But, I don't understand why this string:
>```query(`select "ID", "title", "text" from challenge where "ID"=$/id/`, {id})```
> 
is better than:
>```query(`select "ID", "title", "text" from challenge where "ID"=${id};`)```
>
Second string has no causes for parsing just invoking. First string needs for parsing.
I don't see a reason for using the first variant.

**Comment by vitaly-t** [comment]
Manual query formatting is generally a bad idea, as you expose it to SQL injection + bad escaping.

**Comment by woolfi182** [comment]
I know that it's a bad idea  to make a manual query formatting, but:
1) before I make an injection, I parse and analyze this data
2) I'm not sure that the library, I use, escapes any injections, so I do them manually

I would rather make more analyzing and parse data before making an injection.
I take your viewpoint but I need to sure that the library, I use, parsing and analyzing the data before injecting it.

**Comment by woolfi182** [comment]
After a long deliberation, I understood your viewpoint. Thanks for this.

**Pull request merged**
